name: flutter_buy
description: An Flutter application.
version: 1.0.0


dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  url_launcher: ^3.0.3
  flutter_webview_plugin: ^0.3.0+2
  shared_preferences: ^0.4.3
  event_bus: ^1.0.1
  cupertino_icons: ^0.1.2
  image_picker: ^0.4.10
  barcode_scan: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/ic_avatar_default.png
    - images/ic_nav_tb.png
    - images/ic_nav_pd.png
    - images/ic_nav_jd.png
    - images/ic_zhu.png
    - images/ic_quan.png
    - images/bg_quan.jpg


    - images/meis.png
    - images/meiz.png
    - images/muy.png
    - images/neiy.png
    - images/nvz.png
    - images/riy.png
    - images/shuma.png
    - images/went.png
    - images/xiebao.png
    - images/neiy.png
    - images/nanz.png

    - images/ic_arrow_right.png
    - images/ic_my_blog.png
    - images/ic_my_message.png
    - images/ic_my_question.png
    - images/ic_my_recommend.png
    - images/ic_my_team.png


